version: '3'

services:

  node_server:
    build:
      context: node
    container_name: node_server
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s
    command: npm start
    networks:
      - nodenet
    tty: true
    depends_on:
      - db
  
  db:
    image: mysql:latest
    command: --innodb-use-native-aio=0 --init-file /data/application/init.sql
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet
  
  nginx:
    build:
        context: nginx
    container_name: nginx
    entrypoint: /etc/nginx/start.sh
    networks:
      - nodenet
    ports:
      - "8080:80"
    depends_on:
      - node_server

networks:
  nodenet:
    driver: bridge
